-- Read-only: inspect notification schema, RLS and triggers. No data is changed.
select jsonb_build_object(
 'columns', (select jsonb_agg(to_jsonb(c)) from (select table_name,column_name,data_type,udt_name,is_nullable,column_default from information_schema.columns where table_schema='public' and table_name in ('comments','comment_likes','comment_mentions','notifications','profiles') order by table_name,ordinal_position) c),
 'policies', (select jsonb_agg(to_jsonb(p)) from pg_policies p where schemaname='public' and tablename in ('comments','comment_likes','comment_mentions','notifications','profiles')),
 'rls', (select jsonb_agg(jsonb_build_object('table',c.relname,'enabled',c.relrowsecurity,'forced',c.relforcerowsecurity)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('comments','comment_likes','comment_mentions','notifications','profiles')),
 'constraints', (select jsonb_agg(jsonb_build_object('table',r.relname,'name',c.conname,'definition',pg_get_constraintdef(c.oid))) from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname in ('comments','comment_likes','comment_mentions','notifications','profiles')),
 'triggers', (select jsonb_agg(jsonb_build_object('table',c.relname,'definition',pg_get_triggerdef(t.oid),'function',pg_get_functiondef(t.tgfoid))) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname='public' and c.relname in ('comments','comment_likes','comment_mentions','notifications')),
 'notification_functions', (select jsonb_agg(pg_get_functiondef(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind='f' and p.prosrc ilike '%notifications%')
) as notification_diagnostics;
